# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: gui      
#   password: 9557
#   host: localhost    
  

#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


# development:
#   <<: *default
#   database: search_engine_help_juice_development


# test:
#   <<: *default
#   database: search_engine_help_juice_test


# production:
#   primary: &primary_production
#     <<: *default
#     database: search_engine_help_juice_production
#     username: search_engine_help_juice
#     password: <%= ENV["SEARCH_ENGINE_HELP_JUICE_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: search_engine_help_juice_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: search_engine_help_juice_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: search_engine_help_juice_production_cable
#     migrations_paths: db/cable_migrate

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "gui" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "9557" } %>

development:
  <<: *default
  database: search_engine_help_juice_development

test:
  <<: *default
  database: search_engine_help_juice_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
